import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'

import {
  CircleCheckIcon,
  InfoIcon,
  Loader2Icon,
  OctagonXIcon,
  TriangleAlertIcon,
} from 'lucide-react'

import { ThemeProvider } from '@/components/features/theme-provider'
import { Toaster } from '@/components/ui/sonner'

import './globals.css'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Starter App',
  description: 'Generated by md juwel Rana with Next.js 16',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
          <Toaster
            position="top-right"
            richColors
            icons={{
              success: <CircleCheckIcon className="size-4" />,
              info: <InfoIcon className="size-4" />,
              warning: <TriangleAlertIcon className="size-4" />,
              error: <OctagonXIcon className="size-4" />,
              loading: <Loader2Icon className="size-4 animate-spin" />,
            }}
            style={
              {
                '--normal-bg': 'var(--popover)',
                '--normal-text': 'var(--popover-foreground)',
                '--normal-border': 'var(--border)',
                '--border-radius': 'var(--radius)',
              } as React.CSSProperties
            }
          />
        </ThemeProvider>
      </body>
    </html>
  )
}
