name: Mess App Cron Job

on:
  schedule:
    - cron: '0 2,8,14 * * *'
  workflow_dispatch:

jobs:
  run-cron:
    runs-on: ubuntu-latest
    steps:
      - name: Hit Vercel API
        run: |
          curl -X POST "https://amadermess.vercel.app/api/sendPush" -H "Content-Length: 0"