name: Mess App Cron Job

on:
  schedule:
    # দিনে ৩ বার চলবে (বাংলাদেশ সময় সকাল ৮টা, দুপুর ২টা, এবং রাত ৮টা)
    # গিটহাব UTC টাইম মেনে চলে, তাই ৬ ঘণ্টা মাইনাস করে দেওয়া হয়েছে (2, 5, 14)
    - cron: '0 2,8,10 * * *'

jobs:
  run-cron:
    runs-on: ubuntu-latest
    steps:
      - name: Hit Vercel API
        run: |
          curl -X POST "https://amadermess.vercel.app/api/sendPush" -H "Content-Length: 0"

      # - name: Hit Penalty Check API
      #   run: |
      #     curl -X GET "https://amadermess.vercel.app/api/cron/checkPenalty"